### ISSUE TITLE
changing repo name to haxhub?

### ISSUE THREAD

**Issue by blairanderson** [blairanderson/haxhub#56]
@gschorkopf @novohispano would you guys mind if i change the repo name to haxhub?

In case we want to put it on resumes, it will make more sense. 

or am i reading too much into the whole thing?

**Comment by novohispano** [comment]
I think it make sense. I agree. :)
__
jorge téllez

phone.  720.357.9545
twitter.    @novohispano

**Comment by blairanderson** [comment]
changed. I think the old url will forward.
